title                    : "Anna Rachwalski"
description              : "Tobin Pre-Doctoral Fellow placed in The Budget Lab at Yale University."
url                      : "https://rachwalski-budget-lab.github.io"
baseurl                  : ""
repository               : "rachwalski-budget-lab/rachwalski-budget-lab.github.io"

author:
  name             : "Anna Rachwalski"
  email            : "anna.rachwalski@yale.edu"
  orcid            : "https://orcid.org/0009-0001-6755-6885"
  googlescholar    : "https://scholar.google.com/citations?user=42OfKLQAAAAJ&hl=en"
  linkedin         : "https://www.linkedin.com/in/annarachwalski/"
  github           : "rachwalski-budget-lab"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md

plugins:
  - jekyll-sitemap
