- role: "Host"
  org: "Office Hours With a Social Scientist, PREDOC.org"
  year: "2026"

- role: "Application Reviewer"
  org: "Georgia Governor's Honors Program"
  year: "2025–present"

- role: "Panelist"
  org: "GRAIL Grant Launch Program, UGA School of Law"
  year: "2026"

- role: "Honors Teaching Assistant"
  org: "UGA Honors College, First-Year Honors Seminar"
  year: "2023–2025"

- role: "Facilitator"
  org: "Crisis Communication Think Tank International Symposium, Amsterdam School of Communication Research"
  year: "2025"

- role: "Mentor"
  org: "Peer Assisted Leadership Program, UGA Honors College"
  year: "2023–2026"

- role: "Editorial Board Member"
  org: "Georgia Political Review"
  year: "2022–2024"
